
[defaults]
details = 'app'
state = ""       # This pulls "Using Elgato Capture Card"
large_image = 'switch2_logo'
small_image = 'pfp'

[aliases]
ffplay = 'elgato'
discord = 'elgato'


[unknown]
name = 'Playing Nintendo Switch 2 via ffplay'

[apps.elgato]
name = 'Playing Nintendo Switch 2 via ffplay'
large_image = 'switch2_logo'
small_image= 'pfp'
