
[defaults]
details = "app"
state = ""       # This pulls "Using Elgato Capture Card"
large_image = "switch2_logo"
small_image = "pfp"

[aliases]
ffplay = "elgato"
discord = "elgato"


[unknown]
name = 'Home Menu'

[apps.elgato]
name = 'Home Menu'
large_image = "switch2_logo"
small_image= "pfp"
